messages:
  duelArgs: "/duel <ник>"
  duelYesArgs: "/duel yes <ник>"
  duelNoArgs: "/duel no <ник>"
  duelSpecArgs: "/duel spec <ник>"
  duelOffline: "Игрок (player) оффлайн"
  duelYou: "Нельзя кидать запрос самому себе"
  duelAlreadyFighting: "Игрок (player) уже находится в бою"
  duelAlreadyRequest: "Вы уже отправляли запрос этому игроку. Подождите (time)"
  duelRequestEmpty: "У вас нет запросов на дуэль"
  duelPlayerNotRequest: "Игрок (player) не отправлял вам запрос на дуэль"
  duelRequestTime: "Запрос на дуэль истек"
  duelNo: "Вы отказались от дуэли"
  duelNoSender: "Игрок (player) отказался от дуэли с вами"
  duelNoFighting: "Вы не в бою"
  duelSpectateNoFight: "Игрок (player) не в бою"
  duelSpectateStart: "Вы начали следить за боем игрока (player)"
  duelSpectateStop: "Вы прекратили следить за боем игрока"
  duelSpectateNoPosition: "Ошибка!"
  duelCommandIsBlocked: "Команда запрещена во время дуэли!"
  duelNextRound: "Победил: (player). Количество сыгранных раундов: (round)/(rounds)"
  duelArenasFull: "Свободных арен на данный момент нет!"

  noPermission: "&cНет прав"
  nullPlaceholder: "Нет"
  replaceWinnerNull: "Нет"
  replaceLoserNull: "Нет"
  customReplacer: "Кастомный кит"
  requestSender: "Вы отправили запрос игроку: (player)"
  requestReceiver:
    - "Вас отправил запрос игрок (player)"
    - "Кит: (kit)"
    - "Арена: (arena)"
    - "Количество игр: (numGames)"

  acceptButton: "Принять"
  declineButton: "Отклонить"

  endFight:
    - "ДУЭЛЬ ЗАВЕРШЕНА!!!"
    - "Победил игрок: (winner)"
    - "Проиграл: (loser)"
    - "Количество раундов: (numGames)"
    - "Кит: (kit)"

  startSpectate: "Игрок (player) следит за вашим боем"
  stopSpectate: "Игрок (player) прекратил следить за вашим боем"
  spectateLeave: "Чтобы выйти с дуэли напишите /spec"

  partyHelp:
    - "/party create - создать пати"
    - "/party yes - принять запрос на пати"
    - "/party no - отклонить запрос на пати"
    - "/party disband - распустить пати"
    - "/party leave - выйти с пати"
    - "/party kick - кикнуть игрока с пати"
  partyYesArgs: "/party yes <ник>"
  partyNoArgs: "/party no <ник>"
  partyInviteArgs: "/party invite <ник>"
  partyKickArgs: "/party kick <ник>"
  partyNewOwner: "Вы новый лидер этой группы"
  partyYouLeave: "Вы вышли с этой группы"
  partyLeave: "Игрок (player) вышел с группы"
  partyAlready: "Вы уже находитесь в пати"
  partyAlreadyInvite: "Вы уже пригласили игрока (player)"
  partyAlreadyPlayer: "Игрок (player) уже находится в пати"
  partyNo: "Вы не находитесь в пати"
  partyNoOwner: "Вы не создатель группы"
  partyFullSender: "Ваше пати заполнено!"
  partyFull: "Пати игрока (player) заполнено"
  partyNoPlayer: "Игрок (player) не находится в пати"
  partyNoYourPlayer: "Игрок (player) не находится в вашем пати"
  partyEndDuration: "Время истекло"
  partyJoin: "Вы вступили в пати"
  partyJoinAll: "Игрок (player) вступил в пати"
  partyDecline: "Вы отказались от вступления в группу"
  partyDeclineSender: "Игрок (player) отказался вступать в вашу группу"
  partyInvite: "Вы пригласили игрока (player) в ваше пати"
  partyDisband: "Вы распустили пати"

  partyPlayers:
    - "Лидер: &6&l(owner)"
    - "Игроки: &e(players)"

  partyInvited:
    - "Вас пригласил игрок (player) в свое пати"

  signStartQueue: "Вы встали в очередь с китом (kit)"
  signStopQueue: "Вы вышли с очереди"
  signNoQueue: "Вы не находитесь в очереди"
  signServerReplacer: "Серверный кит: (kit)"
  signCustomReplacer: "Кастомный кит"
  signNoStart: "У вас не установлен кастомный кит!"
  signTextActivate:
    - "Идет бой.."
    - "Между игроками (player)/(player2)"
    - "Тип боя: (type)"

  signTextWait:
    - "Ожидание игроков..."
    - "(players)/(playersMaxSize)"
    - "Тип: (type)"
    - "(kitName)"

  day: "Вы включили день"
  night: "Вы включили ночь"